title: "lowerlee's Notes"
description: "Personal notes, ideas, and references"
markdown: kramdown
highlighter: rouge
url: "https://turtle.supply"
baseurl: ""
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
